export PATH="/home/jason/.config/vifm/scripts:/home/jason/.pyenv/bin:$PATH"

# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M vicmd v edit-command-line
autoload edit-command-line; zle -N edit-command-line

DISABLE_AUTO_TITLE="true"

if (( $+commands[tag] )); then
  export TAG_SEARCH_PROG=rg  # replace with rg for ripgrep
  tag() { command tag "$@"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null }
  alias rg=tag  # replace with rg for ripgrep
fi

# ZSH
export ZSH=/usr/share/oh-my-zsh
export ZSH_THEME="pi"
export ZSH_TMUX_AUTOSTART='false'
export VISUAL=nvim
export DISABLE_AUTO_UPDATE=false
export TERM=screen-256color
export FINDBUGS_HOME=/usr/local/Cellar/findbugs/3.0.1/libexec
[ -f ~/.personal_zsh_jumps ] && source ~/.personal_zsh_jumps
plugins=(history taskwarrior git tmux osx httpie zsh-autosuggestions)

# Pyenv
export PYENV_VERSION=3.10.2
export PYENV_ROOT=/home/jason/.pyenv
export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:${PATH}"
export PYENV_SHELL=zsh
# source '/home/jason/.pyenv/libexec/../completions/pyenv.zsh'


source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Aliases
source ~/.bash_aliases
[ -f ~/.personal_aliases ] && source ~/.personal_aliases

# i3
export TERMINAL=/usr/bin/alacritty

# LS
export CLICOLOR=1
export LSCOLORS=exfxcxdxbxegedabagacxx
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=32:bd=34:cd=34:su=0;41:sg=0;46:tw=0;42:ow=33"
# use LS_COLORS colors in tab completion
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# FZF & FD
FD_OPTIONS="--hidden --follow --no-ignore --exclude .git --exclude mounts"
# FD_OPTIONS="--hidden --follow --exclude .git --exclude node_modules"
# Gimme sexy dracula colors for fzf...
export FZF_DEFAULT_OPTS="--no-mouse -1 --reverse --height 40% --multi --inline-info --preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300' --preview-window='right:hidden:wrap' --bind='f3:execute(bat --style=numbers {} || less -f {}),f2:toggle-preview,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-a:select-all+accept,ctrl-y:execute-silent(echo {+} | pbcopy),ctrl-x:execute(rm -i {+})+abort' --color=dark  --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7"
export FZF_DEFAULT_COMMAND="fd --type f --type l $FD_OPTIONS"
export FZF_CTRL_T_COMMAND="fd $FD_OPTIONS"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"

# Go
export GOROOT=/usr/local/go
export GOPATH=/home/jason/.go
export PATH="/home/jason/bin:$GOPATH/bin:$GOROOT/bin:$PATH"

# Bat
export BAT_PAGER="less -R"
export BAT_THEME="ansi-dark"

# QT. Setting this var forces all QT apps to use GTK+ theme
export QT_QPA_PLATFORMTHEME="qt5ct"

# Functions
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  activate|deactivate|rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}

function auto_pipenv_shell {
    if [ ! -n "${PIPENV_ACTIVE+1}" ]; then
        if [ -f "Pipfile" ] ; then
            pipenv shell
		elif [ -d ".venv" ]; then
			source ./.venv/bin/activate
        fi
    fi
}

function cd {
    builtin cd "$@"
    auto_pipenv_shell
}
